export const COLLECTIONS = {
  USERS: "users",
  STUDENTS: "students",
  TEACHERS: "teachers",
  ADMINS: "admins",
  COURSES: "courses",
  CHAPTERS: "chapters",
  LECTURES: "lectures",
  CLASSES: "classes",
  SESSIONS: "sessions",
  ENROLLMENTS: "enrollments",
  PAYMENTS: "payments",
  INSTALLMENTS: "installments",
  PROMO_CODES: "promoCodes",
  CERTIFICATES: "certificates",
  ANNOUNCEMENTS: "announcements",
  QUIZZES: "quizzes",
  QUIZ_RESULTS: "quizResults",
  VIDEOS: "videos",
  ATTENDANCE: "attendance",
  AUDIT_LOGS: "auditLogs",
  PROGRESS: "progress",
  SETTINGS: "settings",
  SUPPORT_MESSAGES: "supportMessages",
  SECURITY_VIOLATIONS: "securityViolations",
  FINAL_QUIZ_REQUESTS: "finalQuizRequests",
};

export const COURSE_SCHEMA = {
  title: "",
  description: "",
  shortDescription: "",
  category: "",
  level: "beginner",
  teacherId: "",
  teacherName: "",
  price: 0,
  discountPercent: 0,
  status: "draft",
  thumbnail: null,
  chapters: [],
  enrollmentCount: 0,
  completionCount: 0,
  rating: 0,
  ratingCount: 0,
  prerequisites: [],
  hasCertificate: true,
  createdAt: null,
  updatedAt: null,
};

export const CLASS_SCHEMA = {
  name: "",
  batchCode: "",
  teacherId: "",
  teacherName: "",
  startDate: null,
  endDate: null,
  capacity: 30,
  enrolledCount: 0,
  students: [],
  status: "upcoming",
  description: "",
  createdAt: null,
};

export const PAYMENT_SCHEMA = {
  studentId: "",
  studentName: "",
  courseId: "",
  courseName: "",
  amount: 0,
  method: "",
  status: "pending",
  receiptUrl: null,
  reference: "",
  verifiedBy: null,
  verifiedAt: null,
  createdAt: null,
};

export const ENROLLMENT_SCHEMA = {
  studentId: "",
  courseId: "",
  paymentId: "",
  status: "active",
  progress: 0,
  completedAt: null,
  createdAt: null,
};

export const PROMO_CODE_SCHEMA = {
  code: "",
  discountType: "percentage",
  discountValue: 0,
  courseId: null,
  usageLimit: 0,
  usageCount: 0,
  expiresAt: null,
  isActive: true,
  createdAt: null,
};

export const CERTIFICATE_SCHEMA = {
  studentId: "",
  studentName: "",
  courseId: "",
  courseName: "",
  certId: "",
  qrCode: "",
  issuedAt: null,
  createdAt: null,
};
